#include "web_html.h"

const char* HTML_PAGE =
    "HTTP/1.1 200 OK\r\n"
    "Content-Type: text/html\r\n"
    "Connection: close\r\n"
    "\r\n"
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>智能温室控制系统</title>"
    "<script src='https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js'></script>"
    "<style>"
    "* { margin:0; padding:0; box-sizing:border-box; }"
    "body { font-family:'Segoe UI',Arial,sans-serif; background:#0f0f1a; color:#e0e0e0; padding:20px; min-height:100vh; }"
    ".container { max-width:1200px; margin:0 auto; }"
    ".header { text-align:center; padding:30px 20px; background:linear-gradient(135deg,#1a1a2e,#16213e); border-radius:16px; margin-bottom:20px; }"
    ".header h1 { font-size:32px; background:linear-gradient(90deg,#00c853,#00bcd4); -webkit-background-clip:text; -webkit-text-fill-color:transparent; }"
    ".header .subtitle { color:#888; font-size:14px; margin-top:5px; }"
    ".current-data { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:15px; margin-bottom:20px; }"
    ".data-card { background:#1a1a2e; border-radius:12px; padding:20px; text-align:center; border:1px solid #2a2a4a; }"
    ".data-card .icon { font-size:28px; }"
    ".data-card .value { font-size:28px; font-weight:bold; margin:8px 0; }"
    ".data-card .label { font-size:13px; color:#888; }"
    ".data-card.temp .value { color:#ff6b6b; }"
    ".data-card.humi .value { color:#4ecdc4; }"
    ".data-card.light .value { color:#ffd93d; }"
    ".date-selector { display:flex; gap:10px; flex-wrap:wrap; margin-bottom:20px; background:#1a1a2e; padding:15px; border-radius:12px; }"
    ".date-btn { background:#2a2a4a; border:none; color:#aaa; padding:8px 20px; border-radius:20px; cursor:pointer; transition:0.3s; }"
    ".date-btn:hover { background:#3a3a5a; color:#fff; }"
    ".date-btn.active { background:#00c853; color:#fff; }"
    ".charts { display:grid; grid-template-columns:repeat(auto-fit,minmax(300px,1fr)); gap:20px; margin-bottom:20px; }"
    ".chart-box { background:#1a1a2e; border-radius:12px; padding:20px; border:1px solid #2a2a4a; }"
    ".chart-box h3 { color:#aaa; font-size:14px; margin-bottom:10px; text-align:center; }"
    ".chart-container { width:100%; height:250px; }"
    ".control-section { display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-bottom:20px; }"
    ".control-box { background:#1a1a2e; border-radius:12px; padding:20px; border:1px solid #2a2a4a; text-align:center; }"
    ".control-box h3 { color:#aaa; font-size:14px; margin-bottom:15px; }"
    ".ctrl-btn { background:#2a2a4a; border:none; color:#e0e0e0; padding:10px 25px; border-radius:8px; cursor:pointer; margin:5px; transition:0.3s; }"
    ".ctrl-btn:hover { background:#3a3a5a; }"
    ".ctrl-btn.on { background:#00c853; }"
    ".ctrl-btn.on:hover { background:#00e676; }"
    ".ctrl-btn.off { background:#d50000; }"
    ".ctrl-btn.off:hover { background:#ff1744; }"
    ".ctrl-btn.servo { background:#2196f3; }"
    ".ctrl-btn.servo:hover { background:#42a5f5; }"
    ".mode-switch { display:flex; justify-content:center; gap:15px; margin-bottom:15px; }"
    ".mode-btn { background:#2a2a4a; border:none; color:#aaa; padding:8px 30px; border-radius:20px; cursor:pointer; transition:0.3s; }"
    ".mode-btn.active { background:#ff9800; color:#fff; }"
    ".status-bar { background:#1a1a2e; border-radius:12px; padding:15px 20px; border:1px solid #2a2a4a; text-align:center; color:#888; font-size:14px; }"
    ".status-bar span { color:#00c853; }"
    "@media(max-width:600px){ .control-section { grid-template-columns:1fr; } .charts { grid-template-columns:1fr; } }"
    "</style>"
    "</head>"
    "<body>"
    "<div class='container'>"
    "  <div class='header'>"
    "    <h1>🌱 智能温室控制系统</h1>"
    "    <p class='subtitle'>基于 STM32F407 + ESP8266</p>"
    "  </div>"
    "  <div class='current-data'>"
    "    <div class='data-card temp'><div class='icon'>🌡️</div><div class='value' id='temp'>--°C</div><div class='label'>温度</div></div>"
    "    <div class='data-card humi'><div class='icon'>💧</div><div class='value' id='humi'>--%</div><div class='label'>湿度</div></div>"
    "    <div class='data-card light'><div class='icon'>☀️</div><div class='value' id='light'>--</div><div class='label'>光照 (Lux)</div></div>"
    "  </div>"
    "  <div class='date-selector' id='dateSelector'></div>"
    "  <div class='charts'>"
    "    <div class='chart-box'><h3>📈 温度曲线</h3><div class='chart-container' id='chartTemp'></div></div>"
    "    <div class='chart-box'><h3>📈 湿度曲线</h3><div class='chart-container' id='chartHumi'></div></div>"
    "    <div class='chart-box'><h3>📈 光照曲线</h3><div class='chart-container' id='chartLight'></div></div>"
    "  </div>"
    "  <div class='control-section'>"
    "    <div class='control-box'>"
    "      <h3>🔄 工作模式</h3>"
    "      <div class='mode-switch'>"
    "        <button class='mode-btn active' onclick='setMode(\"auto\")'>🤖 自动</button>"
    "        <button class='mode-btn' onclick='setMode(\"manual\")'>✋ 手动</button>"
    "      </div>"
    "    </div>"
    "    <div class='control-box'>"
    "      <h3>🎛️ 手动控制</h3>"
    "      <button class='ctrl-btn on' onclick='controlFan(\"on\")'>风扇 开</button>"
    "      <button class='ctrl-btn off' onclick='controlFan(\"off\")'>风扇 关</button><br>"
    "      <button class='ctrl-btn servo' onclick='controlServo(0)'>0°</button>"
    "      <button class='ctrl-btn servo' onclick='controlServo(45)'>45°</button>"
    "      <button class='ctrl-btn servo' onclick='controlServo(90)'>90°</button>"
    "      <button class='ctrl-btn servo' onclick='controlServo(135)'>135°</button>"
    "      <button class='ctrl-btn servo' onclick='controlServo(180)'>180°</button>"
    "    </div>"
    "  </div>"
    "  <div class='status-bar' id='statusBar'>🟢 系统运行中 | 最后更新: <span id='updateTime'>--</span></div>"
    "</div>"
    "<script>"
    "var chartTemp, chartHumi, chartLight;"
    "var currentDate = getToday();"
    "var mode = 'auto';"
    ""
    "function getToday(){ var d=new Date(); return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'); }"
    ""
    "function getDateStr(offset){ var d=new Date(); d.setDate(d.getDate()+offset); return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'); }"
    ""
    "function initCharts(){"
    "  var common={tooltip:{trigger:'axis'},grid:{left:'5%',right:'5%',bottom:'15%',top:'10%'},xAxis:{type:'category',data:[],axisLabel:{color:'#888',fontSize:10}},yAxis:{type:'value',splitLine:{lineStyle:{color:'#2a2a4a'}},axisLabel:{color:'#888'}}};"
    "  chartTemp=echarts.init(document.getElementById('chartTemp')); chartTemp.setOption(common);"
    "  chartHumi=echarts.init(document.getElementById('chartHumi')); chartHumi.setOption(common);"
    "  chartLight=echarts.init(document.getElementById('chartLight')); chartLight.setOption(common);"
    "}"
    ""
    "function updateCharts(data){"
    "  var times=data.map(function(d){return d.time;});"
    "  chartTemp.setOption({xAxis:{data:times},series:[{type:'line',data:data.map(function(d){return d.temp;}),smooth:true,lineStyle:{color:'#ff6b6b',width:2},itemStyle:{color:'#ff6b6b'}}]});"
    "  chartHumi.setOption({xAxis:{data:times},series:[{type:'line',data:data.map(function(d){return d.humi;}),smooth:true,lineStyle:{color:'#4ecdc4',width:2},itemStyle:{color:'#4ecdc4'}}]});"
    "  chartLight.setOption({xAxis:{data:times},series:[{type:'line',data:data.map(function(d){return d.light;}),smooth:true,lineStyle:{color:'#ffd93d',width:2},itemStyle:{color:'#ffd93d'},areaStyle:{color:'rgba(255,217,61,0.1)'}}]});"
    "}"
    ""
    "function updateDateSelector(){"
    "  var html='';"
    "  var dates=[{label:'今天',offset:0},{label:'昨天',offset:-1},{label:'前天',offset:-2},{label:'3天前',offset:-3},{label:'4天前',offset:-4},{label:'5天前',offset:-5},{label:'6天前',offset:-6}];"
    "  dates.forEach(function(d){ var dateStr=getDateStr(d.offset); var active=(dateStr===currentDate)?'active':''; html+='<button class=\\'date-btn '+active+'\\' onclick=\\'selectDate(\"'+dateStr+'\") \\'>'+d.label+'</button>'; });"
    "  document.getElementById('dateSelector').innerHTML=html;"
    "}"
    ""
    "function selectDate(date){ currentDate=date; updateDateSelector(); fetchHistory(date); }"
    ""
    "function updateCurrentData(){"
    "  fetch('/api/now').then(function(r){return r.json();}).then(function(data){"
    "    document.getElementById('temp').textContent=data.temperature.toFixed(1)+'°C';"
    "    document.getElementById('humi').textContent=data.humidity.toFixed(1)+'%';"
    "    document.getElementById('light').textContent=data.light;"
    "    document.getElementById('updateTime').textContent=new Date().toLocaleTimeString();"
    "  }).catch(function(e){console.log(e);});"
    "}"
    ""
    "function fetchHistory(date){"
    "  fetch('/api/history?date='+date).then(function(r){return r.json();}).then(function(data){"
    "    if(data.data) updateCharts(data.data);"
    "  }).catch(function(e){console.log(e);});"
    "}"
    ""
    "function controlFan(action){"
    "  fetch('/api/control?fan='+action).then(function(r){return r.json();}).then(function(data){"
    "    document.getElementById('statusBar').innerHTML='🟢 风扇: '+action+' | 最后更新: <span id=\\'updateTime\\'>'+new Date().toLocaleTimeString()+'</span>';"
    "  });"
    "}"
    ""
    "function controlServo(angle){"
    "  fetch('/api/control?servo='+angle).then(function(r){return r.json();}).then(function(data){"
    "    document.getElementById('statusBar').innerHTML='🟢 舵机转到 '+angle+'° | 最后更新: <span id=\\'updateTime\\'>'+new Date().toLocaleTimeString()+'</span>';"
    "  });"
    "}"
    ""
    "function setMode(m){ mode=m; document.querySelectorAll('.mode-btn').forEach(function(b){ b.classList.toggle('active',b.textContent.includes(m==='auto'?'自动':'手动')); }); }"
    ""
    "window.onload=function(){ initCharts(); updateDateSelector(); updateCurrentData(); fetchHistory(currentDate); setInterval(updateCurrentData,3000); };"
    "</script>"
    "</body>"
    "</html>";